---

- name: determine name of existing cluster from installation log
  ansible.builtin.include_tasks: '{{ inventory_dir }}/tasks/get_cluster_name.yml'

- name: persist libvirt cluster network configuration
  ansible.builtin.include_tasks: '{{ role_path }}/tasks/persist_libvirt_cluster_network.yml'

- name: persist SSH configuration for easy access to cluster nodes
  ansible.builtin.include_tasks: '{{ role_path }}/tasks/persist_ssh_config.yml'

- name: stop httpd service
  ansible.builtin.service:
    name: httpd.service
    state: stopped

- name: remove the ImageContentSourcePolicy resources referring to the OpenShift image cache
  kubernetes.core.k8s:
    kubeconfig: '{{ openshift_installer_workdir }}/auth/kubeconfig'
    api_version: 'operator.openshift.io/v1alpha1'
    kind: ImageContentSourcePolicy
    name: '{{ item }}'
    state: absent
  loop:
    - image-policy-0
    - image-policy-1
