---

galaxy_info:
  role_name: tuning
  author: Dirk Haubenreisser (haubenr@de.ibm.com)
  description: Role performing performance-related RHOCP cluster configuration tasks
  company: IBM
  license: Apache-2.0
  min_ansible_version: "2.14"
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
    - name: Fedora
      versions:
        - "35"
        - "36"
        - "37"
