---

- name: install and enable libvirt-nss
  block:
    - name: ensure libvirt-nss package is present
      ansible.builtin.dnf:
        name: libvirt-nss
        state: present

    - name: enable libvirt-nss module (RHEL only)
      when: "ansible_distribution == 'RedHat'"
      block:
        - name: add libvirt-nss module to /etc/nsswitch.conf
          ansible.builtin.replace:
            path: /etc/authselect/user-nsswitch.conf
            regexp: '^hosts:.*'
            replace: 'hosts: files libvirt dns myhostname'
            backup: true

        - name: activate change
          ansible.builtin.command:
            cmd: 'authselect apply-changes -b'

    - name: enable libvirt-nss module (Fedora only)
      when: "ansible_distribution == 'Fedora'"
      block:
        - name: add libvirt-nss module to /etc/nsswitch.conf
          ansible.builtin.replace:
            path: /etc/nsswitch.conf
            regexp: '^hosts:.*'
            replace: 'hosts: files libvirt myhostname resolve [!UNAVAIL=return] dns'
            backup: true

- name: enable IPv4 forwarding
  ansible.posix.sysctl:
    name: '{{ item }}'
    value: '1'
    sysctl_set: true
    state: present
    reload: true
  loop:
    - net.ipv4.conf.all.arp_filter
    - net.ipv4.conf.all.proxy_arp
    - net.ipv4.conf.all.forwarding
    - net.ipv4.ip_forward

- name: enable monolithic libvirt
  ansible.builtin.include_tasks: '{{ role_path }}/tasks/enable_monolithic_libvirt.yml'

- name: set the default libvirt connection URI
  ansible.builtin.copy:
    src: '{{ role_path }}/files/libvirt.profile.sh'
    dest: /etc/profile.d/libvirt.sh
    owner: root
    group: root
    mode: '0644'
