apiVersion: tuned.openshift.io/v1
kind: Tuned
metadata:
  name: thp-workers-profile
  namespace: openshift-cluster-node-tuning-operator
spec:
  profile:
    - data: |
        [main]
        summary=Custom tuned profile for RHOCP on IBM Z / LinuxONE to turn off THP on worker nodes
        include=openshift-node

        [vm]
        transparent_hugepages=never
      name: openshift-thp-never-worker
  recommend:
    - match:
        - label: node-role.kubernetes.io/worker
      priority: 35
      profile: openshift-thp-never-worker
