---

galaxy_info:
  role_name: ocp_build_installer
  author: Dirk Haubenreisser (haubenr@de.ibm.com)
  description: Role performing the OpenShift installer binary build
  company: IBM
  license: Apache-2.0
  min_ansible_version: "2.14"
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
    - name: Fedora
      versions:
        - "35"
        - "36"
        - "37"
