---

- name: check if the OCM API token file exists on the Ansible controller
  ansible.builtin.stat:
    path: '{{ ocm_api_token_file }}'
  register: ocm_api_token_file_info
  delegate_to: localhost

- name: compile and install ocm
  when: ocm_api_token_file_info.stat.exists
  block:
    - name: create temporary download directory
      ansible.builtin.tempfile:
        state: directory
        suffix: ocm
      register: temp_dir

    - name: fetch ocm source code
      ansible.builtin.git:
        repo: 'https://github.com/openshift-online/ocm-cli.git'
        dest: '{{ temp_dir.path }}/ocm-cli'
        version: 'v{{ ocm_version }}'
        single_branch: true
        depth: 1

    - name: build ocm binary
      ansible.builtin.command:
        cmd: 'make all'
        chdir: '{{ temp_dir.path }}/ocm-cli'
      environment:
        GOPATH: '{{ temp_dir.path }}/go'
        PATH: '{{ ansible_env.PATH }}:/usr/local/go/bin:{{ temp_dir.path }}/go/bin'
      async: 600
      poll: 10

    - name: remove existing ocm binary from /usr/local/bin
      ansible.builtin.file:
        path: /usr/local/bin/ocm
        state: absent

    - name: copy ocm binary to /usr/local/bin
      ansible.builtin.copy:
        src: '{{ temp_dir.path }}/ocm-cli/ocm'
        dest: /usr/local/bin/ocm
        owner: root
        group: root
        mode: '0755'
        remote_src: true
  always:
    - name: delete temporary download directory
      ansible.builtin.file:
        path: '{{ temp_dir.path }}'
        state: absent
      when: temp_dir.path is defined

- name: archive the cluster in OCM
  when: ocm_api_token_file_info.stat.exists
  block:
    - name: login to OCM
      ansible.builtin.command:
        cmd: '/usr/local/bin/ocm login --token={{ lookup("file", "{{ ocm_api_token_file }}") }}'

    - name: create temporary working directory
      ansible.builtin.tempfile:
        state: directory
        suffix: ocmreq
      register: temp_dir

    - name: generate OCM request payload file
      vars:
        subscription_patch:
          status: Archived
      ansible.builtin.copy:
        dest: '{{ temp_dir.path }}/subscription_patch.json'
        content: '{{ subscription_patch | to_json }}' # noqa jinja[invalid]
        owner: root
        group: root
        mode: '0777'

    - name: determine Subscription resource in OCM assigned to cluster UID
      ansible.builtin.command:
        cmd: '/usr/local/bin/ocm get /api/accounts_mgmt/v1/subscriptions --parameter search="external_cluster_id = ''{{ external_cluster_id }}''"'
      register: ocm_cluster_subscription

    - name: patch Subscription resource in OCM to mark cluster as 'archived'
      when: ocm_cluster_subscription is success
      ansible.builtin.command:
        cmd: '/usr/local/bin/ocm patch /api/accounts_mgmt/v1/subscriptions/{{ ocm_cluster_subscription.stdout | from_json | community.general.json_query("items[0].id") }} --body ''{{ temp_dir.path }}/subscription_patch.json'''
  always:
    - name: delete temporary working directory
      ansible.builtin.file:
        path: '{{ temp_dir.path }}'
        state: absent
      when: temp_dir.path is defined

    - name: logout from OCM
      ansible.builtin.command:
        cmd: '/usr/local/bin/ocm logout'
